apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: Go_Nov6_test 
  janus-idp.io/tekton: Go_Nov6_test
  backstage.io/kubernetes-id: Go_Nov6_test
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: Go_Nov6_test
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  