apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: Go_Nov6_test-gitops
  description: This is GitOps manifest for Go_Nov6_test   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: Go_Nov6_test
    backstage.io/kubernetes-id: Go_Nov6_test 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: Go_Nov6_test   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:Go_Nov6_test
