apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: Go_Nov6_test
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: Go_Nov6_test 
  name: Go_Nov6_test
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: Go_Nov6_test 
